"""empty message

Revision ID: f90c04ad0bee
Revises: 186c35f2027a
Create Date: 2023-03-06 06:47:39.735615+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90c04ad0bee'
down_revision = '186c35f2027a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Book_id'), 'Book', ['id'], unique=False)
    op.create_foreign_key(None, 'Book', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'Books_read', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'Books_read', 'Book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Books_read', type_='foreignkey')
    op.drop_constraint(None, 'Books_read', type_='foreignkey')
    op.drop_constraint(None, 'Book', type_='foreignkey')
    op.drop_index(op.f('ix_Book_id'), table_name='Book')
    # ### end Alembic commands ###
