name: Generate Client API  - Python

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Setup Server"]
    types:
      - completed

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Generate Client API - python
        run: |
          mkdir /tmp/python
          docker run --network=regnify-network --rm -v /tmp/python:/local openapitools/openapi-generator-cli generate -i http://regnify-api:8100/openapi.json -g python -o /local/src \
          -p projectName="regnify-api" \
          -p packageVersion="1.0.$GITHUB_RUN_NUMBER" \
          -p packageName="regnify" \
          -p packageUrl="https://regnify.com"

      - name: Debug folder
        run: ls /tmp/python/src

      # PAT
      - name: Clone Repo into `/tmp/regnify-python.git`
        run: |
          cd /tmp
          git clone https://${{ secrets.PAT }}@github.com/codelorhd/regnify-python-client.git
      
      - name: Update 
        run: cp -r /tmp/python/src/* /tmp/regnify-python/

      - name: Debug folder
        run: ls /tmp/regnify-python/
    
      - name: setup git user
        run: git config --global user.email 'solesty7@gmail.com' && git config --global user.name 'Solomon ABOYEJI'

      - name: Update origin repo if changed (python)
        run: |
          cd /tmp/regnify-python && git add .
          if [[ $(cd /tmp/regnify-python && git status --porcelain | wc -l) -gt 0 ]]
          then
          cd /tmp/regnify-python && git commit -m 'updated repo' && git push 
          else
          echo "not changed locally" 
          fi