name: Setup Server
on: 
  push:
    branches: [ develop, feature/auto-gen-client-packages ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Setup
        run: sudo apt-get update && sudo apt-get install -y make && make create-network --ignore-errors

      # Had to do this to make the run-locally commands compatible (i.e docker-compose)
      - name: Installing docker-compose step - 1
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose;

      - name: Installing docker-compose step - 2
        run: sudo chmod +x /usr/local/bin/docker-compose;

      - name: Start REGNIFY API
        run: make run